services:
  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    #    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
    networks:
      - mediacube-test

  db:
    image: postgres:17-alpine
    container_name: mediacube-db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
    networks:
      - mediacube-test

  redis:
    image: redis:8-alpine
    container_name: mediacube-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - mediacube-test

volumes:
  postgres_data:
  redis_data:

networks:
  mediacube-test:
    driver: bridge
    name: mediacube-test
